# 与 GameSeeder 顺序一致。地图 46、技能 30、怪物 46、物品 145（药水仅 4 血 + 4 魔）。

# 地图背景（横图 640x360）
# 风格：detailed environment, atmospheric lighting, depth layers, rich texture, landscape 16:9, fantasy RPG game background
MAP_PROMPTS = (
    "fantasy RPG game background, safe training camp, green meadow with flowers, tents and banners, wooden fences, warm sunlight, peaceful atmosphere, detailed environment, depth of field",
    "fantasy RPG game background, dark enchanted forest, ancient gnarled trees, dappled shadow, distant wolves, moss and roots, moody atmosphere, volumetric light through canopy",
    "fantasy RPG game background, goblin cave lair, rocky entrance with torches, bones and crates, fire glow, damp stone texture, foreboding mood, detailed cavern",
    "fantasy RPG game background, wild boar plains, rolling grassland, distant hills, tall grass, scattered rocks, golden hour lighting, wide open sky",
    "fantasy RPG game background, treant sacred grove, giant ancient trees, elder tree center, roots and vines, dappled green light, mystical atmosphere, detailed foliage",
    "fantasy RPG game background, dark cave entrance, underground tunnel, stalactites and pools, torch light, dripping water, claustrophobic depth",
    "fantasy RPG game background, spider cave, thick webs, egg sacs, dark cavern with bones, faint glow, creepy detailed texture",
    "fantasy RPG game background, skeleton graveyard, broken tombstones, scattered bones, dead trees, fog, pale moonlight, undead atmosphere",
    "fantasy RPG game background, bone hall, skeleton throne, pillars of bone, dark palace interior, braziers, imposing architecture",
    "fantasy RPG game background, hell gate, lava flows, fire and smoke, demonic portal crack, ember particles, oppressive heat atmosphere",
    "fantasy RPG game background, burning fire plains, lava rivers, volcanic rock, ash fall, orange glow, dramatic sky",
    "fantasy RPG game background, fire demon cave, magma pools, flames and fissures, demonic runes, intense heat haze",
    "fantasy RPG game background, demon fortress, dark castle on lava, spires and battlements, hell sky, dramatic scale",
    "fantasy RPG game background, demon king palace, throne room interior, hell fire braziers, skulls and chains, grand dark architecture",
    "fantasy RPG game background, abyss entrance, void darkness, dark rift in reality, floating debris, cosmic dread",
    "fantasy RPG game background, dark maze, stone corridors, shadows and torches, branching paths, claustrophobic depth",
    "fantasy RPG game background, void rift, space distortion, cosmic swirls, stars and void, dimensional crack",
    "fantasy RPG game background, abyss throne, dark lord seat in void, floating platform, cosmic background, imposing scale",
    "fantasy RPG game background, heaven gate, golden stairs, white clouds, radiant light, divine architecture, hopeful atmosphere",
    "fantasy RPG game background, angel temple, white marble columns, holy light rays, stained glass glow, serene and grand",
    "fantasy RPG game background, hall of glory, golden hall interior, divine murals, warm sacred light, majestic scale",
    "fantasy RPG game background, fallen angel realm, broken pillars, dark wings motif, corrupted heaven, stormy sky",
    "fantasy RPG game background, archangel temple, grand cathedral, high vaulted ceiling, divine light from above, ornate details",
    "fantasy RPG game background, god realm entrance, celestial gate, clouds and stars, golden aura, transcendent scale",
    "fantasy RPG game background, god servant hall, divine servants in background, sacred architecture, soft holy light",
    "fantasy RPG game background, god priest temple, sacred shrine, altars and incense, mystical atmosphere, detailed interior",
    "fantasy RPG game background, god general palace, warrior hall, weapons and banners, divine armor display, martial grandeur",
    "fantasy RPG game background, god king temple, supreme deity throne, highest sanctum, radiant aura, ultimate divine scale",
    "fantasy RPG game background, judgment court, angels of judgment in scene, scales and sword, solemn atmosphere",
    "fantasy RPG game background, eternal gate, timeless portal, swirling time energy, ancient runes, transcendent mood",
    "fantasy RPG game background, time space rift, dimensional crack, fractured reality, multiple layers, cosmic and temporal",
    "fantasy RPG game background, eternal battlefield, endless war, ruins and smoke, distant armies, dramatic sky",
    "fantasy RPG game background, eternal mage tower, tall spire piercing sky, magical aura, glowing windows, dramatic scale",
    "fantasy RPG game background, eternal throne, king of eternity seat, vast hall, timeless architecture, imposing presence",
    "fantasy RPG game background, eternal sanctuary, holy eternal chamber, soft divine light, peaceful sacred space",
    "fantasy RPG game background, chaos gate, chaotic void entrance, unstable reality, swirling colors, ominous portal",
    "fantasy RPG game background, void edge, cosmic void, stars and nebula, endless darkness, vast scale",
    "fantasy RPG game background, chaos rift, chaotic dimension, fractured space, wrong geometry, disturbing atmosphere",
    "fantasy RPG game background, chaos demon hall, dark chaos interior, twisted architecture, demonic and cosmic mix",
    "fantasy RPG game background, chaos origin point, source of chaos, swirling vortex, raw chaotic energy, epic scale",
    "fantasy RPG game background, chaos king throne, final boss arena, lava and void, throne on platform, ultimate battle stage",
    "fantasy RPG game background, chaos origin core, swirling void center, heart of chaos, intense energy",
    "fantasy RPG game background, throne of chaos king, ultimate boss arena, most imposing scene, chaos and fire, final dungeon feel",
)

# 技能图标 1-7 战士 8-15 法师 16-23 游侠 24-30 通用
SKILL_PROMPTS = (
    "RPG skill icon, heavy strike, sword slash motion blur, warrior attack, metallic gleam, impact lines, detailed game UI icon, square, dark background",
    "RPG skill icon, battle roar, war cry sound waves, warrior buff, radiating energy, fierce aura, detailed fantasy icon, square frame, dark background",
    "RPG skill icon, iron wall shield, defense barrier, metallic texture, sturdy design, passive skill, game icon with depth, square, dark background",
    "RPG skill icon, whirlwind slash, spinning sword arc, AOE attack, dynamic motion trail, warrior skill, detailed game art, square, dark background",
    "RPG skill icon, berserk rage, red fury flames, warrior buff, intense glow, anger aura, dramatic lighting, square frame, dark background",
    "RPG skill icon, iron body, armored silhouette, tank passive, metallic sheen, defensive aura, detailed icon design, square, dark background",
    "RPG skill icon, execute finish, sword down strike, execute low HP, decisive blow, impact effect, warrior ultimate feel, square frame, dark background",
    "RPG skill icon, fireball spell, burning orb with flames, mage attack, ember particles, orange glow, detailed magic icon, square, dark background",
    "RPG skill icon, frost nova, ice blast frozen circle, mage AOE, crystalline ice, cold blue glow, frost particles, square frame, dark background",
    "RPG skill icon, mana surge, blue magic flow, passive mana, arcane energy streams, glowing runes, detailed spell icon, square, dark background",
    "RPG skill icon, lightning bolt, thunder strike, mage nuke, electric crackle, yellow white flash, dynamic lightning, square frame, dark background",
    "RPG skill icon, magic shield, arcane barrier, blue translucent barrier, runes, protective glow, mage defense icon, square, dark background",
    "RPG skill icon, arcane wisdom, glowing book or crystal gem, spell power passive, magical aura, detailed fantasy icon, square frame, dark background",
    "RPG skill icon, meteor fall, falling fire rock, mage ultimate, trailing flames, impact glow, dramatic spell icon, square, dark background",
    "RPG skill icon, mana burn, purple vampiric flame, drain mana, dark magic aura, soul drain effect, detailed icon, square frame, dark background",
    "RPG skill icon, piercing shot, single arrow with trail, crit shot, ranger, speed lines, sharp focus, square, dark background",
    "RPG skill icon, multishot, three arrows fanned, volley ranger, dynamic spread, motion blur, detailed game icon, square frame, dark background",
    "RPG skill icon, eagle eye, sharp eye symbol, crit passive ranger, piercing gaze, focus aura, detailed design, square, dark background",
    "RPG skill icon, poison arrow, green toxic arrow, DoT venom drip, ranger, poison haze, detailed fantasy icon, square frame, dark background",
    "RPG skill icon, dodge evade, shadow step, agility blur, afterimage, swift motion, ranger skill icon, square, dark background",
    "RPG skill icon, deadly aim, crosshair target, crit damage passive, precision focus, bullseye glow, detailed icon, square frame, dark background",
    "RPG skill icon, arrow rain, arrows falling from sky, AOE volley, ranger ultimate, raining projectiles, dramatic composition, square, dark background",
    "RPG skill icon, shadow step, blink dagger or backstab, dagger with shadow, stealth aura, detailed game icon, square frame, dark background",
    "RPG skill icon, heal, holy light green plus, heal spell, radiant glow, restorative aura, warm light, square, dark background",
    "RPG skill icon, strength boost, clenched fist or muscle, passive str, power aura, red orange glow, buff icon with depth, square frame, dark background",
    "RPG skill icon, agility boost, boot or wing, passive dex, speed aura, swift motion lines, detailed icon, square, dark background",
    "RPG skill icon, vitality boost, glowing heart, passive vit, life force aura, red pink glow, health buff icon, square frame, dark background",
    "RPG skill icon, energy boost, sparkle or lightning, passive energy, electric glow, power surge, detailed fantasy icon, square, dark background",
    "RPG skill icon, life steal, red vampiric aura, lifedrain passive, blood red glow, soul siphon effect, dramatic icon, square frame, dark background",
    "RPG skill icon, mana regen, blue droplet or pool, mana recovery passive, serene blue glow, flowing magic, detailed spell icon, square, dark background",
)

# 怪物图标
MONSTER_PROMPTS = (
    "RPG monster portrait, wild boar, detailed fur texture, tusks, fierce expression, dynamic pose, soft lighting, game character art, square composition, dark background",
    "RPG monster portrait, wild wolf, muscular beast, sharp fangs, detailed fur, aggressive stance, atmospheric shading, fantasy game art, square frame, dark background",
    "RPG monster portrait, forest goblin, green skin texture, large ears, cunning expression, detailed armor or rags, menacing pose, RPG character design, square, dark background",
    "RPG monster portrait, giant alpha wolf, elite beast, thick fur, glowing eyes, powerful build, detailed anatomy, fantasy creature art, square composition, dark background",
    "RPG monster portrait, treant elder, ancient tree creature, bark texture, twisted branches, wise menacing face, boss character, detailed fantasy art, square frame, dark background",
    "RPG monster portrait, wild boar king, elite boar, larger tusks, scars, royal crown or markings, detailed fur, boss pose, game art style, square, dark background",
    "RPG monster portrait, cave bat, winged creature, detailed wings, fangs, hanging pose, leathery texture, fantasy monster art, square composition, dark background",
    "RPG monster portrait, cave spider, hairy legs, multiple eyes, venomous fangs, creepy detailed texture, crouching pose, RPG enemy art, square frame, dark background",
    "RPG monster portrait, skeleton soldier, undead warrior, bone details, rusted armor, menacing stance, dark fantasy art, square composition, dark background",
    "RPG monster portrait, skeleton mage, undead caster, robe and bones, magical aura, staff or orb, elite enemy design, detailed fantasy art, square, dark background",
    "RPG monster portrait, bone king, skeleton boss, crown, ornate armor, imposing pose, detailed bones and regalia, boss character art, square frame, dark background",
    "RPG monster portrait, giant spider, elite spider, larger scale, detailed mandibles, venom drip, intimidating pose, fantasy creature art, square composition, dark background",
    "RPG monster portrait, small demon imp, horns, tail, hell creature, mischievous expression, detailed skin texture, RPG enemy art, square frame, dark background",
    "RPG monster portrait, fire elemental, flame creature, burning form, embers, dynamic fire shape, fantasy elemental art, square composition, dark background",
    "RPG monster portrait, hell knight, demon warrior, armor and flames, horns, elite enemy, detailed design, dark fantasy game art, square frame, dark background",
    "RPG monster portrait, hell demon king, boss, crown, wings, imposing presence, detailed demon design, ultimate boss art, square composition, dark background",
    "RPG monster portrait, fire demon, magma creature, molten cracks, flame aura, menacing pose, detailed fantasy art, square frame, dark background",
    "RPG monster portrait, demon wizard, elite caster, robes, horns, magical energy, staff, detailed character design, RPG boss art, square, dark background",
    "RPG monster portrait, abyss worm, void creature, segmented body, teeth, cosmic dark texture, lovecraftian style, square composition, dark background",
    "RPG monster portrait, shadow ghost, dark spirit, ethereal form, haunting face, wispy details, fantasy undead art, square frame, dark background",
    "RPG monster portrait, void walker, elite void creature, humanoid shadow, glowing eyes, dimensional rift details, detailed fantasy art, square, dark background",
    "RPG monster portrait, abyss lord, void boss, imposing dark figure, crown or horns, cosmic aura, boss character design, square composition, dark background",
    "RPG monster portrait, angel guardian, holy warrior, white armor, wings, divine light, detailed character, fantasy angel art, square frame, dark background",
    "RPG monster portrait, seraph, six wings, flaming angel, radiant details, majestic pose, detailed fantasy art, square composition, dark background",
    "RPG monster portrait, archangel, elite angel, armor and wings, sword or staff, powerful presence, game character design, square, dark background",
    "RPG monster portrait, fallen angel, dark wings, corrupted holy armor, menacing expression, detailed design, dark fantasy art, square frame, dark background",
    "RPG monster portrait, archangel chief, angel boss, crown, grand wings, imposing holy figure, boss character art, square composition, dark background",
    "RPG monster portrait, temple knight, holy knight, ornate armor, sacred symbols, noble pose, detailed fantasy design, square, dark background",
    "RPG monster portrait, divine servant, god servant, celestial robes, serene yet powerful, detailed character, fantasy game art, square frame, dark background",
    "RPG monster portrait, divine messenger, god envoy, wings, scroll or trumpet, majestic pose, detailed design, square composition, dark background",
    "RPG monster portrait, divine general, god warrior, heavy armor, divine weapon, commanding pose, elite character art, square, dark background",
    "RPG monster portrait, divine priest, god priest, holy vestments, staff, wise expression, detailed fantasy design, square frame, dark background",
    "RPG monster portrait, god king avatar, supreme deity form, crown, divine aura, ultimate boss presence, highly detailed character art, square composition, dark background",
    "RPG monster portrait, judgment angel, elite judge, scales or sword, stern expression, wings, detailed design, square, dark background",
    "RPG monster portrait, eternal guardian, eternal warrior, ancient armor, timeless design, powerful stance, detailed fantasy art, square frame, dark background",
    "RPG monster portrait, time space rift creature, dimensional crack entity, cosmic form, swirling void, abstract yet characterful, square composition, dark background",
    "RPG monster portrait, eternal warrior, elite eternal, armored figure, eternal symbols, detailed design, fantasy game art, square, dark background",
    "RPG monster portrait, eternal mage, eternal caster, robes, arcane symbols, magical aura, detailed character, square frame, dark background",
    "RPG monster portrait, eternal king, eternal boss, crown, throne aura, imposing figure, boss character design, square composition, dark background",
    "RPG monster portrait, eternal knight, elite knight, ornate eternal armor, weapon, detailed fantasy design, square, dark background",
    "RPG monster portrait, chaos sprite, chaos creature, unstable form, chaotic energy, twisted design, detailed fantasy art, square frame, dark background",
    "RPG monster portrait, void lord, void boss, dark cosmic figure, rift details, imposing presence, boss character art, square composition, dark background",
    "RPG monster portrait, chaos warrior, elite chaos, armor with chaos symbols, weapon, fierce pose, detailed design, square, dark background",
    "RPG monster portrait, chaos demon god, chaos elite, demonic and cosmic mix, horns wings, powerful design, detailed fantasy art, square frame, dark background",
    "RPG monster portrait, chaos origin, source of chaos boss, abstract monstrous form, swirling chaos, ultimate entity design, square composition, dark background",
    "RPG monster portrait, chaos king, final boss, crown, chaos aura, most imposing figure, highly detailed final boss art, square, dark background",
)

# 物品图标（与 game_item_definitions.id 一致，顺序与 GameSeederData/items.php 相同，药水仅 4 血 + 4 魔在末尾）
# 风格：detailed game item icon, material texture, soft shading, square, transparent background
ITEM_PROMPTS = (
    "RPG item icon, beginner sword, simple blade, metallic sheen, leather grip, detailed game item, soft shading, square, transparent background",
    "RPG item icon, iron sword, iron blade, dull metal texture, crossguard, detailed game item, soft shading, square, transparent background",
    "RPG item icon, steel sword, polished steel blade, edge gleam, detailed game item, soft shading, square, transparent background",
    "RPG item icon, rune sword, blade with runes, magical glow along edge, detailed game item, soft shading, square, transparent background",
    "RPG item icon, dragon fang sword, fang-shaped blade, dragon bone texture, detailed game item, soft shading, square, transparent background",
    "RPG item icon, titan sword, massive blade, heavy metal, imposing design, detailed game item, soft shading, square, transparent background",
    "RPG item icon, paladin sword, holy blade, golden crossguard, sacred aura, detailed game item, soft shading, square, transparent background",
    "RPG item icon, berserker sword, brutal blade, jagged edge, fierce design, detailed game item, soft shading, square, transparent background",
    "RPG item icon, angel sword, angelic blade, white gold glow, wing motif, detailed game item, soft shading, square, transparent background",
    "RPG item icon, holy judgment sword, divine blade, judgment light, ornate hilt, detailed game item, soft shading, square, transparent background",
    "RPG item icon, god king sword, supreme blade, divine radiance, royal design, detailed game item, soft shading, square, transparent background",
    "RPG item icon, eternal blade sword, eternal metal, timeless glow, detailed game item, soft shading, square, transparent background",
    "RPG item icon, chaos cleaver sword, chaotic blade, unstable edge, dark energy, detailed game item, soft shading, square, transparent background",
    "RPG item icon, beginner staff, wooden wizard staff, simple orb or knot, detailed game item, soft shading, square, transparent background",
    "RPG item icon, oak staff, oak wood grain, natural texture, detailed game item, soft shading, square, transparent background",
    "RPG item icon, crystal staff, crystal top, magical glow, detailed game item, soft shading, square, transparent background",
    "RPG item icon, moon staff, crescent moon finial, pale glow, detailed game item, soft shading, square, transparent background",
    "RPG item icon, star staff, star-shaped crystal, starlight aura, detailed game item, soft shading, square, transparent background",
    "RPG item icon, void staff, void crystal, dark cosmic glow, detailed game item, soft shading, square, transparent background",
    "RPG item icon, arcane staff, arcane runes, blue magic aura, detailed game item, soft shading, square, transparent background",
    "RPG item icon, phoenix staff, phoenix motif, flame aura, detailed game item, soft shading, square, transparent background",
    "RPG item icon, angel staff, angel wing finial, holy light, detailed game item, soft shading, square, transparent background",
    "RPG item icon, archmage staff, grand design, powerful magic glow, detailed game item, soft shading, square, transparent background",
    "RPG item icon, divine revelation staff, divine symbol, radiant glow, detailed game item, soft shading, square, transparent background",
    "RPG item icon, eternal mana source staff, eternal crystal, mana flow aura, detailed game item, soft shading, square, transparent background",
    "RPG item icon, chaos wand, short chaos wand, chaotic energy, detailed game item, soft shading, square, transparent background",
    "RPG item icon, beginner bow, simple wooden bow, string, detailed game item, soft shading, square, transparent background",
    "RPG item icon, long bow, elongated bow, wood grain, detailed game item, soft shading, square, transparent background",
    "RPG item icon, elf bow, elegant curve, elven design, detailed game item, soft shading, square, transparent background",
    "RPG item icon, demon hunter bow, grim design, dark metal trim, detailed game item, soft shading, square, transparent background",
    "RPG item icon, shadow bow, shadow-touched wood, dark aura, detailed game item, soft shading, square, transparent background",
    "RPG item icon, wind god bow, wind motif, flowing lines, detailed game item, soft shading, square, transparent background",
    "RPG item icon, elf king bow, royal elven design, ornate, detailed game item, soft shading, square, transparent background",
    "RPG item icon, phoenix feather bow, feather motif, ember glow, detailed game item, soft shading, square, transparent background",
    "RPG item icon, angel bow, angelic design, holy aura, detailed game item, soft shading, square, transparent background",
    "RPG item icon, marksman bow, precision design, clean lines, detailed game item, soft shading, square, transparent background",
    "RPG item icon, divine hunter bow, divine design, radiant trim, detailed game item, soft shading, square, transparent background",
    "RPG item icon, eternal hunter bow, eternal wood, timeless glow, detailed game item, soft shading, square, transparent background",
    "RPG item icon, chaos piercer bow, chaotic design, piercing aura, detailed game item, soft shading, square, transparent background",
    "RPG item icon, cloth cap helmet, fabric cap, simple stitching, detailed game item, soft shading, square, transparent background",
    "RPG item icon, leather cap helmet, leather helmet, straps, detailed game item, soft shading, square, transparent background",
    "RPG item icon, iron helmet, iron helm, metal texture, visor, detailed game item, soft shading, square, transparent background",
    "RPG item icon, mithril helmet, mithril metal, silvery sheen, detailed game item, soft shading, square, transparent background",
    "RPG item icon, dragon bone helmet, dragon bone, horn motif, detailed game item, soft shading, square, transparent background",
    "RPG item icon, holy helmet, holy symbol, divine light, detailed game item, soft shading, square, transparent background",
    "RPG item icon, paladin helmet, paladin design, cross or crown, detailed game item, soft shading, square, transparent background",
    "RPG item icon, angel helmet, angel wing motif, white gold, detailed game item, soft shading, square, transparent background",
    "RPG item icon, divine helmet, divine radiance, ornate design, detailed game item, soft shading, square, transparent background",
    "RPG item icon, eternal helmet, eternal metal, timeless aura, detailed game item, soft shading, square, transparent background",
    "RPG item icon, chaos helmet, chaos spikes, dark energy, detailed game item, soft shading, square, transparent background",
    "RPG item icon, creation helmet, creation tier, powerful aura, detailed game item, soft shading, square, transparent background",
    "RPG item icon, god king helmet, supreme crown helm, divine glory, detailed game item, soft shading, square, transparent background",
    "RPG item icon, cloth robe armor, fabric robe, simple trim, detailed game item, soft shading, square, transparent background",
    "RPG item icon, leather armor, leather cuirass, straps and buckles, detailed game item, soft shading, square, transparent background",
    "RPG item icon, chain mail armor, metal rings, metallic texture, detailed game item, soft shading, square, transparent background",
    "RPG item icon, plate armor, steel plates, armor segments, detailed game item, soft shading, square, transparent background",
    "RPG item icon, mithril armor, mithril plates, silvery gleam, detailed game item, soft shading, square, transparent background",
    "RPG item icon, dragon scale armor, scale texture, dragon hide, detailed game item, soft shading, square, transparent background",
    "RPG item icon, divine armor, divine light, sacred symbols, detailed game item, soft shading, square, transparent background",
    "RPG item icon, paladin armor, paladin plate, holy insignia, detailed game item, soft shading, square, transparent background",
    "RPG item icon, angel armor, angelic plate, wing motifs, detailed game item, soft shading, square, transparent background",
    "RPG item icon, holy armor, holy plate, radiant design, detailed game item, soft shading, square, transparent background",
    "RPG item icon, eternal armor, eternal metal, timeless design, detailed game item, soft shading, square, transparent background",
    "RPG item icon, chaos armor, chaos plate, dark spikes, detailed game item, soft shading, square, transparent background",
    "RPG item icon, creation armor, creation tier plate, powerful glow, detailed game item, soft shading, square, transparent background",
    "RPG item icon, god king armor, supreme armor, divine radiance, detailed game item, soft shading, square, transparent background",
    "RPG item icon, cloth gloves, fabric gloves, simple, detailed game item, soft shading, square, transparent background",
    "RPG item icon, leather gloves, leather gauntlets, stitching, detailed game item, soft shading, square, transparent background",
    "RPG item icon, iron gauntlets, iron gloves, metal plates, detailed game item, soft shading, square, transparent background",
    "RPG item icon, steel gauntlets, steel gloves, polished metal, detailed game item, soft shading, square, transparent background",
    "RPG item icon, dragon skin gloves, dragon scale texture, detailed game item, soft shading, square, transparent background",
    "RPG item icon, power gloves, reinforced design, strength aura, detailed game item, soft shading, square, transparent background",
    "RPG item icon, paladin gloves, holy gauntlets, sacred trim, detailed game item, soft shading, square, transparent background",
    "RPG item icon, angel gloves, angelic gauntlets, white gold, detailed game item, soft shading, square, transparent background",
    "RPG item icon, divine gloves, divine gauntlets, radiant, detailed game item, soft shading, square, transparent background",
    "RPG item icon, eternal gloves, eternal metal gloves, timeless, detailed game item, soft shading, square, transparent background",
    "RPG item icon, chaos gloves, chaos claws, dark energy, detailed game item, soft shading, square, transparent background",
    "RPG item icon, creation gloves, creation tier gauntlets, powerful, detailed game item, soft shading, square, transparent background",
    "RPG item icon, god king gloves, supreme gauntlets, divine glory, detailed game item, soft shading, square, transparent background",
    "RPG item icon, cloth boots, fabric boots, simple, detailed game item, soft shading, square, transparent background",
    "RPG item icon, leather boots, leather boots, stitching, detailed game item, soft shading, square, transparent background",
    "RPG item icon, iron boots, iron greaves, metal texture, detailed game item, soft shading, square, transparent background",
    "RPG item icon, swift boots, lightweight design, speed aura, detailed game item, soft shading, square, transparent background",
    "RPG item icon, ranger boots, ranger style, flexible leather, detailed game item, soft shading, square, transparent background",
    "RPG item icon, phantom boots, shadow-touched, ethereal trim, detailed game item, soft shading, square, transparent background",
    "RPG item icon, paladin boots, holy greaves, sacred design, detailed game item, soft shading, square, transparent background",
    "RPG item icon, angel boots, angelic greaves, white gold, detailed game item, soft shading, square, transparent background",
    "RPG item icon, god speed boots, divine speed, radiant trim, detailed game item, soft shading, square, transparent background",
    "RPG item icon, eternal boots, eternal metal boots, timeless, detailed game item, soft shading, square, transparent background",
    "RPG item icon, chaos boots, chaos greaves, dark energy, detailed game item, soft shading, square, transparent background",
    "RPG item icon, creation boots, creation tier boots, powerful, detailed game item, soft shading, square, transparent background",
    "RPG item icon, god king boots, supreme greaves, divine glory, detailed game item, soft shading, square, transparent background",
    "RPG item icon, cloth belt, fabric belt, simple buckle, detailed game item, soft shading, square, transparent background",
    "RPG item icon, leather belt, leather belt, metal buckle, detailed game item, soft shading, square, transparent background",
    "RPG item icon, iron belt, iron belt, metal plates, detailed game item, soft shading, square, transparent background",
    "RPG item icon, giant belt, massive belt, strength design, detailed game item, soft shading, square, transparent background",
    "RPG item icon, life belt, life symbol, vitality aura, detailed game item, soft shading, square, transparent background",
    "RPG item icon, titan belt, titan design, heavy metal, detailed game item, soft shading, square, transparent background",
    "RPG item icon, paladin belt, holy belt, sacred buckle, detailed game item, soft shading, square, transparent background",
    "RPG item icon, angel belt, angelic belt, divine trim, detailed game item, soft shading, square, transparent background",
    "RPG item icon, divine belt, divine belt, radiant buckle, detailed game item, soft shading, square, transparent background",
    "RPG item icon, eternal belt, eternal metal belt, timeless, detailed game item, soft shading, square, transparent background",
    "RPG item icon, chaos belt, chaos belt, dark energy, detailed game item, soft shading, square, transparent background",
    "RPG item icon, creation belt, creation tier belt, powerful, detailed game item, soft shading, square, transparent background",
    "RPG item icon, god king belt, supreme belt, divine glory, detailed game item, soft shading, square, transparent background",
    "RPG item icon, copper ring, copper band, simple metal, detailed game item, soft shading, square, transparent background",
    "RPG item icon, silver ring, silver band, metallic sheen, detailed game item, soft shading, square, transparent background",
    "RPG item icon, gold ring, gold band, golden glow, detailed game item, soft shading, square, transparent background",
    "RPG item icon, ruby ring, ruby gem, red glow, metal band, detailed game item, soft shading, square, transparent background",
    "RPG item icon, sapphire ring, sapphire gem, blue glow, metal band, detailed game item, soft shading, square, transparent background",
    "RPG item icon, jade ring, jade stone, green glow, detailed game item, soft shading, square, transparent background",
    "RPG item icon, raven ring, raven motif, dark gem, detailed game item, soft shading, square, transparent background",
    "RPG item icon, stone of jordan ring, legendary ring, blue stone, detailed game item, soft shading, square, transparent background",
    "RPG item icon, dwarf ring, dwarf craft, sturdy band, detailed game item, soft shading, square, transparent background",
    "RPG item icon, magic ring, magical glow, enchanted band, detailed game item, soft shading, square, transparent background",
    "RPG item icon, paladin ring, holy ring, sacred symbol, detailed game item, soft shading, square, transparent background",
    "RPG item icon, angel ring, angelic ring, divine glow, detailed game item, soft shading, square, transparent background",
    "RPG item icon, divine ring, divine band, radiant gem, detailed game item, soft shading, square, transparent background",
    "RPG item icon, eternal ring, eternal metal, timeless glow, detailed game item, soft shading, square, transparent background",
    "RPG item icon, chaos ring, chaos band, dark gem, detailed game item, soft shading, square, transparent background",
    "RPG item icon, creation ring, creation tier ring, powerful glow, detailed game item, soft shading, square, transparent background",
    "RPG item icon, god king ring, supreme ring, divine radiance, detailed game item, soft shading, square, transparent background",
    "RPG item icon, wooden amulet, wooden pendant, natural grain, detailed game item, soft shading, square, transparent background",
    "RPG item icon, bone amulet, bone pendant, carved design, detailed game item, soft shading, square, transparent background",
    "RPG item icon, crystal amulet, crystal pendant, soft glow, detailed game item, soft shading, square, transparent background",
    "RPG item icon, lion amulet, lion motif pendant, detailed game item, soft shading, square, transparent background",
    "RPG item icon, cat eye amulet, cat eye stone, green shimmer, detailed game item, soft shading, square, transparent background",
    "RPG item icon, marshal amulet, marshal insignia, authoritative design, detailed game item, soft shading, square, transparent background",
    "RPG item icon, infernal amulet, infernal pendant, fire glow, detailed game item, soft shading, square, transparent background",
    "RPG item icon, sacred amulet, sacred symbol, holy light, detailed game item, soft shading, square, transparent background",
    "RPG item icon, paladin amulet, paladin symbol, sacred design, detailed game item, soft shading, square, transparent background",
    "RPG item icon, angel amulet, angel pendant, divine glow, detailed game item, soft shading, square, transparent background",
    "RPG item icon, sacred angel amulet, sacred angel symbol, radiant, detailed game item, soft shading, square, transparent background",
    "RPG item icon, eternal amulet, eternal pendant, timeless glow, detailed game item, soft shading, square, transparent background",
    "RPG item icon, chaos amulet, chaos pendant, dark energy, detailed game item, soft shading, square, transparent background",
    "RPG item icon, creation amulet, creation tier pendant, powerful aura, detailed game item, soft shading, square, transparent background",
    "RPG item icon, god king amulet, supreme amulet, divine glory, detailed game item, soft shading, square, transparent background",
    # 药水 4 血 + 4 魔（与 items.php 一致：轻型→生命/法力→强效→超级，用尺寸量词区分）
    # 仅生成药水: python -m rpg_map_bg items 138 145
    # 轻型生命药水：微型红色生命药水，小玻璃瓶，拇指大小，红色液体发光，软木塞（仅一瓶、单物）
    "RPG item icon, single tiny red health potion only, one small glass vial alone, thumb-sized bottle, red liquid glow, cork, no multiple bottles no duplicates, single object in frame, detailed game item, soft shading, square, transparent background",
    # 生命药水：小型红色生命药水，中号玻璃瓶，掌心大小，深红液体，标签
    "RPG item icon, small red health potion, one medium glass bottle, palm-sized vessel, crimson liquid, label, detailed game item, soft shading, square, transparent background",
    # 强效生命药水：强效红色生命药水，大玻璃瓶，拳头大小，发光红色液体
    "RPG item icon, strong red health potion, one big glass bottle, fist-sized flask, glowing red liquid, detailed game item, soft shading, square, transparent background",
    # 超级生命药水：超级红色生命药水，超大玻璃瓶，前臂大小华丽容器，明亮红光
    "RPG item icon, super red health potion, one extra-large glass bottle, forearm-sized ornate vessel, bright red glow, detailed game item, soft shading, square, transparent background",
    # 轻型法力药水：微型蓝色法力药水，小玻璃瓶，拇指大小，蓝色液体发光，软木塞
    "RPG item icon, tiny blue mana potion, one small glass vial, thumb-sized bottle, blue liquid glow, cork, detailed game item, soft shading, square, transparent background",
    # 法力药水：小型蓝色法力药水，中号玻璃瓶，掌心大小，天蓝液体，标签
    "RPG item icon, small blue mana potion, one medium glass bottle, palm-sized vessel, azure liquid, label, detailed game item, soft shading, square, transparent background",
    # 强效法力药水：强效蓝色法力药水，大玻璃瓶，拳头大小，发光蓝色液体
    "RPG item icon, strong blue mana potion, one big glass bottle, fist-sized flask, glowing blue liquid, detailed game item, soft shading, square, transparent background",
    # 超级法力药水：超级蓝色法力药水，超大玻璃瓶，前臂大小华丽容器，明亮蓝光
    "RPG item icon, super blue mana potion, one extra-large glass bottle, forearm-sized ornate vessel, bright blue glow, detailed game item, soft shading, square, transparent background",
)